# Welcome to Jekyll!
#
# About Theme
#
# Yet another theme for elegant writers with modern flat style and beautiful
# night/dark mode.
#
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Adventure Engineering
email: ''
author: Julia Baribeau

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
#
copyright: "Copyleft (cleft) {currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  Adventure Engineering: a blog dedicated to sharing inspiring examples of sustainable innovation 
  and resilient problem-solving from anywhere in the world.

#baseurl: "/adventuneering" # the subpath of your site, e.g. /blog
url: "https://baribeau.github.io" # the base hostname & protocol for your site, e.g. https://example.com
favicon: "/assets/images/favicon.png" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%d %b %Y"

# If you want more debug log, you can set true
debug: false

# If you don't want transparent header, you can set false
header_transparent: true

# If you want to change the content width, you can set to another value
content_width: "920px"

# Google analytics - GA4
# google_analytics: [Measurement ID]
# enableDNT: "false"

# If you want to generate website sitemap, you can set true
sitemap: true

# If you want to change site language, you can set lang option
lang: "en"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    #img: https://cdn.countryflags.com/thumbs/england/flag-400.png
    text: English

  - lang: fr
    #img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: Français

  - lang: hi
    #img: https://cdn.countryflags.com/thumbs/india/flag-400.png
    text: हिंदी

  - lang: ne
    #img: https://cdn.countryflags.com/thumbs/nepal/flag-400.png
    text: नेपाली

  - lang: id
    #img: https://cdn.countryflags.com/thumbs/indonesia/flag-400.png
    text: Bahasa Indonesia

  - lang: ms
    #img: https://cdn.countryflags.com/thumbs/malaysia/flag-400.png
    text: Bahasa Malaysia

  - lang: tl
    #img: https://cdn.countryflags.com/thumbs/philippines/flag-400.png
    text: Tagalog

  - lang: km
    #img: https://cdn.countryflags.com/thumbs/cambodia/flag-400.png
    text: ខ្មែរ

  - lang: th
    #img: https://cdn.countryflags.com/thumbs/thailand/flag-400.png
    text: ไทย

  - lang: vi
    #img: https://cdn.countryflags.com/thumbs/vietnam/flag-400.png
    text: Tiếng Việt

  - lang: ko
    #img: https://cdn.countryflags.com/thumbs/south-korea/flag-400.png
    text: 한국어

  - lang: zh
    #img: https://cdn.countryflags.com/thumbs/china/flag-400.png
    text: 中文-简体

  - lang: ja
    #img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: 日本語

  - lang: pt
    #img: https://cdn.countryflags.com/thumbs/portugal/flag-400.png
    text: Português

  - lang: es
    #img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
    text: Espanol

  - lang: de
    #img: https://cdn.countryflags.com/thumbs/germany/flag-400.png
    text: Deutsch

  - lang: nl
    #img: https://cdn.countryflags.com/thumbs/netherlands/flag-400.png
    text: Nederlands

# Greyscales
richblack: "#020404"
eerieblack: "#1c2121"
gunmetal: "#394141"
dimgrey: "#687575"
silver: "#afb7b7"
seasalt: "#f6f8f8"

# Gradient blue-greens
cerulean: "#2b778c"
vividskyblue: "#46c5ea"
tiffanyblue: "#75d3d7"
celadon: "#a3e0c3"
teagreen: "#c2e9b6"
mindaro: "#e9f5a8"

# Gradient oranges
goldengate: "#E7480D" #orange (dark)
giantsorange: "#f86624" #orange (med)
coral: "#FA814A" #orange (light)
atomictangerine: "#FAA077" #orange (very light)

# Accent colours if needed
africanviolet: "#af8ccf" #purple (light)
tekhelet: "#4c2c69" #purple (dark)
oxfordblue: "#102542" #blue (dark)
darkgreen: "#002500" #green (dark)
xanthous: "#fbb637" #yellow (med)
rosered: "#b9314f" #pinkish-red (dark)

# Colour settings
theme_color: seasalt
brand_color: goldengate


# You can custom selection style
# selection:
#   color: "#ff0000"
#   background_color: "#ffff00"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)

night_mode: "auto"

# Code badge setting
# You can enable or disable the code badge and so on
code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#ff4e00"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - about.html
  - tags.html
  #- categories.html
  - archives.html

# Page default value
defaults:
  home:
    heading: "Welcome to Adventure Engineering!"
    subheading: "Exploring solutions together"
    banner: "/assets/images/banners/oceanbanner.jpg"

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
banner:
  video: null             # Video banner source
  loop: true              # Video loop
  volume: 0               # Video volume (100% is 1.0)
  start_at: 0             # Video start time
  image: null             # Image banner source
  opacity: 1.0            # Banner opacity (100% is 1.0)
  background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
  height: "640px"         # Banner default height
  min_height: null        # Banner minimum height
  heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
  subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt settings
excerpt:
  default_image: /assets/images/default-image.jpeg  # Default image when the image style is not none
  image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
  image_width: 38.2%      # Image default width
  image_height: 160px     # Image default height
  text_size: 350          # Words default size

# Pagination setting
paginate: 5

# Photo previewer settings (PhotoSwipe 5)
# the options please refer to: https://photoswipe.com/options/
photo_previewer:
 gallery: "section.main"
 children: "a.photo-swipe"
 bgOpacity: 0.8
 padding:
   top: 20
   bottom: 40
   left: 100
   right: 100

# Click to top settings
click_to_top:
  light:
    background_color: seasalt
    color: dimgrey
  dark:
    background_color: giantsorange
    color: silver

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Utterances comments
# See https://utteranc.es/
# set follow_site_theme true to make utterances' theme follow the site's

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true

# Build settings
# highlighter: none
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
